---
title: "Depression"
author: "Shuyi Bian, Carmina Inguito, Yutong Ji"
date: "2/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(ggthemes)
library(shiny)
library(shinydashboard)
```

```{r}
options(scipen=999) #cancels the use of scientific notation for the session
```

## Import Data
```{r}
depression <- readr::read_csv("b_depressed.csv")
```
```{r}
depression_tidy <- clean_names(depression)
```

```{r}
naniar::miss_var_summary(depression_tidy)
```

## Rename Columns
```{r}
depression_tidy <- depression_tidy %>% 
  rename(durable_investment = lasting_investment,
         nondurable_investment = no_lasting_investmen)
```

## Make categories

```{r}
depression_tidy <- depression_tidy %>% 
  mutate(sex_category = case_when(sex == 1 ~ "female",
                                  sex == 0 ~ "male"))
```

```{r}
depression_tidy <- depression_tidy %>% 
  mutate(married_category = case_when(married == 1 ~ "married",
                                      married == 0 ~ "unmarried"))
```

```{r}
depression_tidy <- depression_tidy %>% 
  mutate(depressed_category = case_when(depressed == 1 ~ "depressed",
                                        depressed == 0 ~ "not depressed"))
```

```{r}
depression_tidy <- depression_tidy %>% 
  mutate(age_category = case_when(age <= 14 ~ "children",
                                  age >= 15 & age <= 24 ~ "youth",
                                  age >= 25 & age <= 64 ~ "adult",
                                  age >= 65 ~ "senior"))
```

```{r}
depression_tidy <- depression_tidy %>% 
  mutate(education_category = case_when(education_level <= 8 ~ "basic",
                                        education_level >= 9 & education_level <= 12 ~ "secondary",
                                        education_level >= 13 ~ "high"))
```


